name: Configure SSH
description: Set up SSH configuration file

inputs:
  ssh_user:
    description: User to use on SSH login
    required: true
  ssh_ip:
    description: IP address to SSH to
    required: true
  ssh_private_key:
    description: Private key to use on SSH connection
    required: true

runs:
  using: composite
  steps:
    - name: Create configuration file
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/deploy-key.pem
        chmod 600 ~/.ssh/deploy-key.pem
        cat >> ~/.ssh/config <<END
        Host my-vps
          HostName ${{ inputs.ssh_ip }}
          User ${{ inputs.ssh_user }}
          IdentityFile ~/.ssh/deploy-key.pem
          StrictHostKeyChecking no
        END
      shell: bash
