name: Send Status
description: Send activity status via Discord webhook

inputs:
  webhook:
    description: Discord webhook URL
    required: true
  branch:
    description: Deploment branch (e.g. main, dev)
    required: true
  status:
    description: Status of deployed service (0 for success, 1 for failure)
    required: true
  activity:
    description: Name of activity (sentence case, e.g. Back end deployment, React tests)
    required: true

runs:
  using: composite
  steps:
    - name: Build status string
      run: |
        if [[ "${{ input.status }}" == 0 ]]
        then
          deployment_status="- status: success ✅"
        elif [[ "${{ input.status }}" == 1 ]]
          deployment_status="- status: failure 🚨"
        else
          deployment_status="- status: unknown ❓"
        fi
      shell: bash
    - name: Send message
      run: |
        curl -s -X POST "${{ input.webhook }}" \
          -d "content=${{ inputs.activity }} on branch \`${{ inputs.branch }}\` ${deployment_status}"
      shell: bash
