name: Send Deploy Status
description: Send deployment status via Discord webhook

inputs:
  webhook:
    description: Discord webhook URL
    required: true
  branch:
    description: Deploment branch (e.g. main, dev)
    required: true
  status:
    description: Status of deployed service (0 for success, 1 for failure)
    required: true
  service:
    description: Name of deployed service (e.g. back end, front end)

runs:
  using: composite
  steps:
    - name: Build status string
      run: |
        if [[ "${{ input.status }}" == 0 ]]
        then
          deployment_status="success 🚀"
        elif [[ "${{ input.status }}" == 1 ]]
          deployment_status="failure 🚨"
        else
          deployment_status="status unknown ❓"
        fi
      shell: bash
    - name: Send message
      run: |
        curl -s -X POST "${{ input.webhook }}" \
          -d "content=Deployment of ${{ inputs.service }} on branch \`${{ inputs.branch }}\` ${deployment_status}"
      shell: bash
