name: Deploy to main VPS
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      environment: main

  fetch-latest-commit:
    name: Fetch latest main commit from VPS
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH connection
        uses: ./.github/actions/configure-ssh
        with:
          ssh_user: ${{ secrets.MAIN_SSH_USER }}
          ssh_ip: ${{ secrets.MAIN_SSH_IP }}
          ssh_private_key: ${{ secrets.MAIN_SSH_PRIVATE_KEY }}

      - name: Fetch latest commit
        run: ssh my-vps 'cd ${{ secrets.PROJECT_ROOT }} && git fetch && git reset origin/main --hard'

  deploy-back-end:
    name: Deploy back end to VPS
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH connection
        uses: ./.github/actions/configure-ssh
        with:
          ssh_user: ${{ secrets.MAIN_SSH_USER }}
          ssh_ip: ${{ secrets.MAIN_SSH_IP }}
          ssh_private_key: ${{ secrets.MAIN_SSH_PRIVATE_KEY }}

      - name: Deploy server
        run: ssh my-vps 'cd ${{ secrets.PROJECT_ROOT }}/backend-dashboard-2/ && ./redeploy.sh'

      - name: Retrieve server status
        run: ssh my-vps 'ps a | grep puma | grep -v grep'

      - name: Send Discord message on success
        if: ${{ success() }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Back end deployment to \`main\` VPS successful"

      - name: Send Discord message on failure
        if: ${{ failure() }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Back end deployment to \`main\` VPS failed"

  deploy-front-end:
    name: Deploy back end to VPS
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH connection
        uses: ./.github/actions/configure-ssh
        with:
          ssh_user: ${{ secrets.MAIN_SSH_USER }}
          ssh_ip: ${{ secrets.MAIN_SSH_IP }}
          ssh_private_key: ${{ secrets.MAIN_SSH_PRIVATE_KEY }}

      - name: Deploy client
        run: ssh my-vps 'cd ${{ secrets.PROJECT_ROOT }}/client/ && ./redeploy.sh'

      - name: Retrieve client status
        run: ssh my-vps 'ps a | grep http-server | grep -v grep'

      - name: Send Discord message on success
        if: ${{ success() }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Front end deployment to \`main\` VPS successful"

      - name: Send Discord message on failure
        if: ${{ failure() }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Front end deployment to \`main\` VPS failed"
