name: Run Tests
on:
  pull_request:
    branches:
      - main
      - dev
  workflow_call:
    inputs:
      environment:
        required: false
        type: string

jobs:
  test-client:
    runs-on: ubuntu-latest
    name: Run React client tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add React test suite setup

      - name: Run tests
        run: cd client/ && ./run_test.sh

      - name: Send Discord message on failure
        if: ${{ failure() && ( inputs.environment == 'dev' || inputs.environment == 'main' ) }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=⚠️ React tests for \`${{ inputs.environment }}\` deployment failed"

  test-server:
    runs-on: ubuntu-latest
    name: Run Ruby server tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add Rails test suite setup

      - name: Run tests
        run: cd backend-dashboard-2/ && ./run_test.sh

      - name: Send Discord message on failure
        if: ${{ failure() && ( inputs.environment == 'dev' || inputs.environment == 'main' ) }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=⚠️ Rails tests for \`${{ inputs.environment }}\` deployment failed"
